name: beat_the_crowd
channels:
  - cyclus
  - anaconda
  - defaults
dependencies:
  - altair=4.1.0=py_1
  - anyio=3.5.0=py310haa95532_0
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py310h2bbff1b_0
  - arrow-cpp=8.0.0=py310h38b8b19_1
  - astroid=2.14.2=py310haa95532_0
  - asttokens=2.0.5=pyhd3eb1b0_0
  - attrs=22.1.0=py310haa95532_0
  - aws-c-common=0.4.57=ha925a31_1
  - aws-c-event-stream=0.1.6=hd77b12b_5
  - aws-checksums=0.1.9=ha925a31_0
  - aws-sdk-cpp=1.8.185=hd77b12b_0
  - babel=2.11.0=py310haa95532_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - beautifulsoup4=4.11.1=py310haa95532_0
  - blas=1.0=mkl
  - bleach=4.1.0=pyhd3eb1b0_0
  - blinker=1.4=py310haa95532_0
  - boost-cpp=1.73.0=h2bbff1b_12
  - bottleneck=1.3.5=py310h9128911_0
  - brotlipy=0.7.0=py310h2bbff1b_1002
  - bzip2=1.0.8=he774522_0
  - c-ares=1.18.1=h2bbff1b_0
  - ca-certificates=2023.01.10=haa95532_0
  - cachetools=4.2.2=pyhd3eb1b0_0
  - certifi=2022.12.7=py310haa95532_0
  - cffi=1.15.1=py310h2bbff1b_3
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=8.0.4=py310haa95532_0
  - colorama=0.4.6=py310haa95532_0
  - comm=0.1.2=py310haa95532_0
  - commonmark=0.9.1=pyhd3eb1b0_0
  - cryptography=39.0.1=py310h21b164f_0
  - dataclasses=0.8=pyh6d0b6a4_7
  - debugpy=1.5.1=py310hd77b12b_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - dill=0.3.6=py310haa95532_0
  - entrypoints=0.4=py310haa95532_0
  - executing=0.8.3=pyhd3eb1b0_0
  - flit-core=3.6.0=pyhd3eb1b0_0
  - freetype=2.12.1=ha860e81_0
  - future=0.18.3=py310haa95532_0
  - gflags=2.2.2=ha925a31_0
  - giflib=5.2.1=h8cc25b3_3
  - gitdb=4.0.7=pyhd3eb1b0_0
  - gitpython=3.1.30=py310haa95532_0
  - glib=2.69.1=h5dc1a3c_2
  - glog=0.5.0=hd77b12b_0
  - gst-plugins-base=1.18.5=h9e645db_0
  - gstreamer=1.18.5=hd78058f_0
  - icu=58.2=ha925a31_3
  - idna=3.4=py310haa95532_0
  - importlib-metadata=4.11.3=py310haa95532_0
  - intel-openmp=2021.4.0=haa95532_3556
  - ipykernel=6.19.2=py310h9909e9c_0
  - ipython=8.10.0=py310haa95532_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - ipywidgets=7.6.5=pyhd3eb1b0_1
  - isort=5.9.3=pyhd3eb1b0_0
  - java-jdk=8.25.17=0
  - jedi=0.18.1=py310haa95532_1
  - jinja2=3.1.2=py310haa95532_0
  - jpeg=9e=h2bbff1b_1
  - json5=0.9.6=pyhd3eb1b0_0
  - jsonschema=4.17.3=py310haa95532_0
  - jupyter=1.0.0=py310haa95532_8
  - jupyter_client=7.4.9=py310haa95532_0
  - jupyter_console=6.6.2=py310haa95532_0
  - jupyter_core=5.2.0=py310haa95532_0
  - jupyter_server=1.23.4=py310haa95532_0
  - jupyterlab=3.5.3=py310haa95532_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_server=2.19.0=py310haa95532_0
  - jupyterlab_widgets=1.0.0=pyhd3eb1b0_1
  - lazy-object-proxy=1.6.0=py310h2bbff1b_0
  - lerc=3.0=hd77b12b_0
  - libboost=1.73.0=h6c2663c_12
  - libbrotlicommon=1.0.9=h2bbff1b_7
  - libbrotlidec=1.0.9=h2bbff1b_7
  - libbrotlienc=1.0.9=h2bbff1b_7
  - libclang=12.0.0=default_h627e005_2
  - libcurl=7.87.0=h86230a5_0
  - libdeflate=1.17=h2bbff1b_0
  - libffi=3.4.2=hd77b12b_6
  - libiconv=1.16=h2bbff1b_2
  - libogg=1.3.5=h2bbff1b_1
  - libpng=1.6.39=h8cc25b3_0
  - libprotobuf=3.20.3=h23ce68f_0
  - libsodium=1.0.18=h62dcd97_0
  - libssh2=1.10.0=hcd4344a_0
  - libthrift=0.15.0=he1d8c1a_0
  - libtiff=4.5.0=h6c2663c_2
  - libvorbis=1.3.7=he774522_0
  - libwebp=1.2.4=hbc33d0d_1
  - libwebp-base=1.2.4=h2bbff1b_1
  - libxml2=2.9.14=h0ad7f3c_0
  - libxslt=1.1.35=h2bbff1b_0
  - lxml=4.9.1=py310h1985fb9_0
  - lz4-c=1.9.4=h2bbff1b_0
  - markupsafe=2.1.1=py310h2bbff1b_0
  - matplotlib-inline=0.1.6=py310haa95532_0
  - mccabe=0.7.0=pyhd3eb1b0_0
  - mistune=0.8.4=py310h2bbff1b_1000
  - mkl=2021.4.0=haa95532_640
  - mkl-service=2.4.0=py310h2bbff1b_0
  - mkl_fft=1.3.1=py310ha0764ea_0
  - mkl_random=1.2.2=py310h4ed8f06_0
  - nbclassic=0.5.2=py310haa95532_0
  - nbclient=0.5.13=py310haa95532_0
  - nbconvert=6.5.4=py310haa95532_0
  - nbformat=5.7.0=py310haa95532_0
  - nest-asyncio=1.5.6=py310haa95532_0
  - notebook=6.5.2=py310haa95532_0
  - notebook-shim=0.2.2=py310haa95532_0
  - numexpr=2.8.4=py310hd213c9f_0
  - numpy=1.23.5=py310h60c9a35_0
  - numpy-base=1.23.5=py310h04254f7_0
  - openjdk=11.0.13=h2bbff1b_0
  - openssl=1.1.1t=h2bbff1b_0
  - packaging=22.0=py310haa95532_0
  - pandas=1.5.3=py310h4ed8f06_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pcre=8.45=hd77b12b_0
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=9.4.0=py310hd77b12b_0
  - pip=22.3.1=py310haa95532_0
  - platformdirs=2.5.2=py310haa95532_0
  - plotly=5.9.0=py310haa95532_0
  - ply=3.11=py310haa95532_0
  - prometheus_client=0.14.1=py310haa95532_0
  - prompt-toolkit=3.0.36=py310haa95532_0
  - prompt_toolkit=3.0.36=hd3eb1b0_0
  - protobuf=3.20.3=py310hd77b12b_0
  - psutil=5.9.0=py310h2bbff1b_0
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - py4j=0.10.9.3=py310haa95532_0
  - pyarrow=8.0.0=py310h26aae1b_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pydeck=0.7.1=py310haa95532_0
  - pygments=2.11.2=pyhd3eb1b0_0
  - pylint=2.16.2=py310haa95532_0
  - pympler=0.9=py_0
  - pyodbc=4.0.34=py310hd77b12b_0
  - pyopenssl=23.0.0=py310haa95532_0
  - pyqt=5.15.7=py310hd77b12b_0
  - pyqt5-sip=12.11.0=py310hd77b12b_0
  - pyrsistent=0.18.0=py310h2bbff1b_0
  - pysocks=1.7.1=py310haa95532_0
  - pyspark=3.2.1=py310haa95532_0
  - python=3.10.9=h966fe2a_1
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-fastjsonschema=2.16.2=py310haa95532_0
  - pytz=2022.7=py310haa95532_0
  - pywin32=305=py310h2bbff1b_0
  - pywinpty=2.0.10=py310h5da7b33_0
  - pyyaml=6.0=py310h2bbff1b_1
  - pyzmq=23.2.0=py310hd77b12b_0
  - qt-main=5.15.2=he8e5bd7_7
  - qt-webengine=5.15.9=hb9a9bb5_5
  - qtpy=2.2.0=py310haa95532_0
  - qtwebkit=5.212=h3ad3cdb_4
  - re2=2022.04.01=hd77b12b_0
  - requests=2.28.1=py310haa95532_0
  - rich=12.5.1=py310haa95532_0
  - semver=2.13.0=pyhd3eb1b0_0
  - send2trash=1.8.0=pyhd3eb1b0_1
  - setuptools=65.6.3=py310haa95532_0
  - sip=6.6.2=py310hd77b12b_0
  - six=1.16.0=pyhd3eb1b0_1
  - smmap=4.0.0=pyhd3eb1b0_0
  - snappy=1.1.9=h6c2663c_0
  - sniffio=1.2.0=py310haa95532_1
  - soupsieve=2.3.2.post1=py310haa95532_0
  - sqlite=3.40.1=h2bbff1b_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - tenacity=8.0.1=py310haa95532_1
  - terminado=0.17.1=py310haa95532_0
  - tinycss2=1.2.1=py310haa95532_0
  - tk=8.6.12=h2bbff1b_0
  - toml=0.10.2=pyhd3eb1b0_0
  - tomli=2.0.1=py310haa95532_0
  - tomlkit=0.11.1=py310haa95532_0
  - toolz=0.12.0=py310haa95532_0
  - tornado=6.2=py310h2bbff1b_0
  - traitlets=5.7.1=py310haa95532_0
  - typing-extensions=4.4.0=py310haa95532_0
  - typing_extensions=4.4.0=py310haa95532_0
  - tzdata=2022g=h04d1e81_0
  - tzlocal=2.1=py310haa95532_1
  - urllib3=1.26.14=py310haa95532_0
  - utf8proc=2.6.1=h2bbff1b_0
  - validators=0.18.2=pyhd3eb1b0_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - watchdog=2.1.6=py310haa95532_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py310haa95532_1
  - websocket-client=0.58.0=py310haa95532_4
  - wheel=0.38.4=py310haa95532_0
  - widgetsnbextension=3.5.2=py310haa95532_0
  - win_inet_pton=1.1.0=py310haa95532_0
  - wincertstore=0.2=py310haa95532_2
  - winpty=0.4.3=4
  - wrapt=1.14.1=py310h2bbff1b_0
  - xz=5.2.10=h8cc25b3_1
  - yaml=0.2.5=he774522_0
  - zeromq=4.3.4=hd77b12b_0
  - zipp=3.11.0=py310haa95532_0
  - zlib=1.2.13=h8cc25b3_0
  - zstd=1.5.2=h19a0ad4_0
  - pip:
    - findspark==2.0.1
    - patsy==0.5.3
    - plotly-express==0.4.1
    - qtconsole==5.4.0
    - scipy==1.10.1
    - statsmodels==0.13.5
    - streamlit==1.19.0
