name: environment.yml
channels:
  - plotly
  - defaults
dependencies:
  - appdirs=1.4.4=pyhd3eb1b0_0
  - blas=1.0=mkl
  - bottleneck=1.3.5=py310h9128911_0
  - brotlipy=0.7.0=py310h2bbff1b_1002
  - bzip2=1.0.8=he774522_0
  - ca-certificates=2023.01.10=haa95532_0
  - certifi=2022.12.7=py310haa95532_0
  - cffi=1.15.1=py310h2bbff1b_3
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - cryptography=39.0.1=py310h21b164f_0
  - icc_rt=2022.1.0=h6049295_2
  - idna=3.4=py310haa95532_0
  - intel-openmp=2021.4.0=haa95532_3556
  - libffi=3.4.2=hd77b12b_6
  - mkl=2021.4.0=haa95532_640
  - mkl-service=2.4.0=py310h2bbff1b_0
  - mkl_fft=1.3.1=py310ha0764ea_0
  - mkl_random=1.2.2=py310h4ed8f06_0
  - numexpr=2.8.4=py310hd213c9f_0
  - numpy=1.23.5=py310h60c9a35_0
  - numpy-base=1.23.5=py310h04254f7_0
  - openssl=1.1.1t=h2bbff1b_0
  - packaging=22.0=py310haa95532_0
  - pandas=1.5.3=py310h4ed8f06_0
  - patsy=0.5.3=py310haa95532_0
  - pip=23.0.1=py310haa95532_0
  - plotly=5.9.0=py310haa95532_0
  - plotly_express=0.4.0=py_0
  - pooch=1.4.0=pyhd3eb1b0_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyopenssl=23.0.0=py310haa95532_0
  - pysocks=1.7.1=py310haa95532_0
  - python=3.10.9=h966fe2a_2
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - pytz=2022.7=py310haa95532_0
  - requests=2.28.1=py310haa95532_0
  - scipy=1.10.0=py310hb9afe5d_1
  - setuptools=65.6.3=py310haa95532_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.40.1=h2bbff1b_0
  - statsmodels=0.13.5=py310h9128911_1
  - tenacity=8.0.1=py310haa95532_1
  - tk=8.6.12=h2bbff1b_0
  - tzdata=2022g=h04d1e81_0
  - urllib3=1.26.14=py310haa95532_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wheel=0.38.4=py310haa95532_0
  - win_inet_pton=1.1.0=py310haa95532_0
  - wincertstore=0.2=py310haa95532_2
  - xz=5.2.10=h8cc25b3_1
  - zlib=1.2.13=h8cc25b3_0
prefix: C:\Users\franc\miniconda3\envs\environment.yml
